language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

  # command to install dependencies
install:
  #- pip install pandas
  - python setup.py install
  - pip install coveralls
  - pip install pathos
  - pip install numpy
  - pip install matplotlib
  - pip install scipy
  - pip install pandas
  - pip install pytest pytest-pep8 pytest-cov
  # Use docutils to generate html describe
  - pip install docutils
  #- pip install matplotlib
  #- travis_wait pip install scipy

script:
  - pip uninstall spotpy -y
  - py.test  spotpy/unittests/test_* spotpy/examples/tutorial_rosenbrock.py  --cov spotpy --cov-report term-missing -v

after_success:
  - coveralls
